//! Thin macOS boundary: NSPasteboard, frontmost app, ⌘V synthesis, Accessibility.
//!
//! Everything here goes through audited `objc2-app-kit` / `core-graphics`
//! bindings. The unavoidable Accessibility C FFI boundaries carry local
//! SAFETY arguments.

use std::sync::{Mutex, OnceLock};
use std::time::{Duration, Instant};

use objc2::rc::Retained;
use objc2::runtime::AnyObject;
use objc2::{define_class, msg_send, sel, AnyThread};
use objc2_app_kit::{
    NSApplicationActivationOptions, NSPasteboard, NSRunningApplication, NSWorkspace,
    NSWorkspaceApplicationKey, NSWorkspaceDidActivateApplicationNotification,
};
use objc2_foundation::{MainThreadMarker, NSData, NSNotification, NSObject, NSObjectProtocol, NSString};

/// True when the caller is already on the AppKit main thread.
///
/// `MainThreadMarker::new()` is `Some` only on the main thread, which is
/// exactly the question, and it costs one `NSThread.isMainThread` check.
pub fn is_main_thread() -> bool {
    MainThreadMarker::new().is_some()
}

/// Queues `work` onto the main thread via libdispatch, without blocking.
///
/// This deliberately does NOT go through `AppHandle::run_on_main_thread`.
/// That posts to tao's event-loop proxy, and tao only drains that queue while
/// it is processing events — but Raff is an accessory (`LSUIElement`) app that
/// sits with no visible window most of the time, so its loop is parked and
/// nothing drains. Measured on a cold launch, a panel-show posted that way
/// took 2.5 SECONDS to run, and sometimes did not run at all until an
/// unrelated event happened along. Waking CFRunLoop first does not help: the
/// loop wakes, but tao still is not iterating, so its queue stays untouched.
///
/// libdispatch's main queue is drained by AppKit's own run-loop integration,
/// which is always installed, so work lands on the next turn regardless of
/// what tao is doing. `exec_async` (not `exec_sync`/`run_on_main`, which
/// block and could deadlock against a caller already holding a lock the main
/// thread wants) keeps the calling thread free.
pub fn dispatch_to_main<F: FnOnce() + Send + 'static>(work: F) {
    dispatch2::DispatchQueue::main().exec_async(work);
}

/// Pasteboard flags set by password managers and other sensitive sources.
/// Content carrying these must never be stored (see plan §5).
const CONCEALED_TYPES: [&str; 2] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
];

const TYPE_TEXT: &str = "public.utf8-plain-text";
const TYPE_HTML: &str = "public.html";
const TYPE_RTF: &str = "public.rtf";
const TYPE_PNG: &str = "public.png";
const TYPE_TIFF: &str = "public.tiff";

/// Rich representations larger than this are not stored (keeps the JSON store lean).
const MAX_RICH_BYTES: usize = 256 * 1024;

/// Raw pasteboard content, as captured. `rtf`/`html` are kept so a normal paste
/// can restore formatting while "paste as plain text" writes only `text`.
#[derive(Default)]
pub struct RawClip {
    pub text: Option<String>,
    pub html: Option<String>,
    pub rtf: Option<Vec<u8>>,
    pub png: Option<Vec<u8>>,
    pub tiff: Option<Vec<u8>>,
}

#[derive(Clone, Debug, Default)]
pub struct FrontApp {
    pub pid: i32,
    pub name: String,
    pub bundle_id: String,
}

pub fn change_count() -> isize {
    NSPasteboard::generalPasteboard().changeCount()
}

pub fn has_concealed_type() -> bool {
    let pb = NSPasteboard::generalPasteboard();
    let Some(types) = pb.types() else {
        return false;
    };
    types
        .iter()
        .any(|t| CONCEALED_TYPES.contains(&t.to_string().as_str()))
}

pub fn read_clip() -> RawClip {
    let pb = NSPasteboard::generalPasteboard();
    let string_for = |t: &str| {
        pb.stringForType(&NSString::from_str(t))
            .map(|s| s.to_string())
    };
    let data_for = |t: &str| {
        pb.dataForType(&NSString::from_str(t))
            .map(|d| d.to_vec())
            .filter(|d| !d.is_empty())
    };

    let text = string_for(TYPE_TEXT);
    let html = string_for(TYPE_HTML).filter(|h| h.len() <= MAX_RICH_BYTES);
    let rtf = data_for(TYPE_RTF).filter(|d| d.len() <= MAX_RICH_BYTES);
    // Only bother with image data when there is no text representation.
    let (png, tiff) = if text.as_deref().map(|t| !t.trim().is_empty()) == Some(true) {
        (None, None)
    } else {
        (data_for(TYPE_PNG), data_for(TYPE_TIFF))
    };

    RawClip {
        text,
        html,
        rtf,
        png,
        tiff,
    }
}

/// Writes the given representations to the general pasteboard and returns the
/// new change count only when at least one requested representation was
/// accepted (so callers never report copy/paste success for a rejected write).
pub fn write_clip(
    text: Option<&str>,
    html: Option<&str>,
    rtf: Option<&[u8]>,
    png: Option<&[u8]>,
) -> Option<isize> {
    let pb = NSPasteboard::generalPasteboard();
    pb.clearContents();
    let mut accepted = false;
    if let Some(t) = text {
        accepted |= pb.setString_forType(&NSString::from_str(t), &NSString::from_str(TYPE_TEXT));
    }
    if let Some(h) = html {
        accepted |= pb.setString_forType(&NSString::from_str(h), &NSString::from_str(TYPE_HTML));
    }
    if let Some(r) = rtf {
        accepted |= pb.setData_forType(Some(&NSData::with_bytes(r)), &NSString::from_str(TYPE_RTF));
    }
    if let Some(p) = png {
        accepted |= pb.setData_forType(Some(&NSData::with_bytes(p)), &NSString::from_str(TYPE_PNG));
    }
    accepted.then(|| pb.changeCount())
}

pub fn frontmost_app() -> FrontApp {
    let ws = NSWorkspace::sharedWorkspace();
    match ws.frontmostApplication() {
        Some(app) => FrontApp {
            pid: app.processIdentifier(),
            name: app
                .localizedName()
                .map(|s| s.to_string())
                .unwrap_or_default(),
            bundle_id: app
                .bundleIdentifier()
                .map(|s| s.to_string())
                .unwrap_or_default(),
        },
        None => FrontApp::default(),
    }
}

/// One frontmost-app change, as NSWorkspace reported it: the app that took the
/// front and the instant it did.
#[derive(Clone, Debug)]
pub struct Activation {
    pub at: Instant,
    pub app: FrontApp,
}

/// Activations older than this are dropped on the next write. The capture path
/// never looks back further than one poll interval, so this is generous.
const ACTIVATION_KEEP: Duration = Duration::from_secs(10);

fn activation_log() -> &'static Mutex<Vec<Activation>> {
    static LOG: OnceLock<Mutex<Vec<Activation>>> = OnceLock::new();
    LOG.get_or_init(|| Mutex::new(Vec::new()))
}

/// Records `app` as owning the front from now on, oldest entry first.
pub fn note_activation(app: FrontApp) {
    let now = Instant::now();
    let mut log = activation_log()
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner());
    let cutoff = now.checked_sub(ACTIVATION_KEEP).unwrap_or(now);
    // Keep the newest activation at or before the cutoff: it is the one still
    // in force, and dropping it would lose the answer for older windows.
    let keep_from = log
        .iter()
        .rposition(|a| a.at <= cutoff)
        .unwrap_or(0);
    log.drain(..keep_from);
    log.push(Activation { at: now, app });
}

/// Snapshot of the activation log, oldest first.
pub fn activation_snapshot() -> Vec<Activation> {
    activation_log()
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner())
        .clone()
}

/// True when any app that held the front during `[at - window, at]` is excluded.
///
/// An activation at `t` means that app owned the front from `t` until the next
/// one, so the window covers the activation in force when it opened plus every
/// activation inside it — not only the newest, which is all `frontmost_app()`
/// can answer, and which is exactly what the copy-then-switch race defeats.
pub fn window_has_excluded(
    log: &[Activation],
    excluded: &[String],
    at: Instant,
    window: Duration,
) -> bool {
    let is_excluded = |a: &Activation| excluded.iter().any(|e| *e == a.app.bundle_id);
    front_when_window_opened(log, at, window).is_some_and(is_excluded)
        || log
            .iter()
            .filter(|a| a.at > window_start(at, window) && a.at <= at)
            .any(is_excluded)
}

/// The app that held the front when the window opened — the best available
/// guess at who owned a copy detected at `at`. `None` when the log does not
/// reach that far back.
pub fn front_at(log: &[Activation], at: Instant, window: Duration) -> Option<FrontApp> {
    front_when_window_opened(log, at, window).map(|a| a.app.clone())
}

fn window_start(at: Instant, window: Duration) -> Instant {
    at.checked_sub(window).unwrap_or(at)
}

/// The newest activation at or before the window opened — the one still in
/// force when it did. `None` when the log does not reach that far back.
fn front_when_window_opened(
    log: &[Activation],
    at: Instant,
    window: Duration,
) -> Option<&Activation> {
    let start = window_start(at, window);
    log.iter().rev().find(|a| a.at <= start)
}

define_class!(
    // SAFETY:
    // - The superclass NSObject has no subclassing requirements.
    // - `ActivationObserver` does not implement `Drop`.
    #[unsafe(super(NSObject))]
    #[name = "RaffActivationObserver"]
    struct ActivationObserver;

    impl ActivationObserver {
        #[unsafe(method(raffAppDidActivate:))]
        fn raff_app_did_activate(&self, notification: &NSNotification) {
            note_activation(activated_app(notification));
        }
    }

    unsafe impl NSObjectProtocol for ActivationObserver {}
);

/// The app named by a `NSWorkspaceDidActivateApplication` notification, falling
/// back to whoever is frontmost if the payload is not the expected shape.
fn activated_app(notification: &NSNotification) -> FrontApp {
    notification
        .userInfo()
        .and_then(|info| {
            // SAFETY: `NSWorkspaceApplicationKey` is an AppKit string constant,
            // valid for the lifetime of the process.
            let key: &NSString = unsafe { NSWorkspaceApplicationKey };
            let key: &AnyObject = key.as_ref();
            info.objectForKey(key)
        })
        .and_then(|value| value.downcast::<NSRunningApplication>().ok())
        .map(|app| FrontApp {
            pid: app.processIdentifier(),
            name: app
                .localizedName()
                .map(|s| s.to_string())
                .unwrap_or_default(),
            bundle_id: app
                .bundleIdentifier()
                .map(|s| s.to_string())
                .unwrap_or_default(),
        })
        .unwrap_or_else(frontmost_app)
}

/// Starts recording app activations, so a capture can ask who held the front
/// during the window a copy happened in rather than who holds it now.
///
/// Registration and delivery are main-thread work, so it hops there; calling
/// this more than once would register a second observer, so `start` is the only
/// caller.
pub fn start_activation_watch() {
    dispatch_to_main(|| {
        note_activation(frontmost_app());
        let observer = ActivationObserver::new();
        let center = NSWorkspace::sharedWorkspace().notificationCenter();
        // SAFETY: the observer responds to `raffAppDidActivate:` with the
        // (self, NSNotification *) signature AppKit posts, the name is an
        // AppKit constant, and the observer is leaked below so it outlives the
        // registration — NSNotificationCenter holds it unowned.
        unsafe {
            center.addObserver_selector_name_object(
                observer.as_ref(),
                sel!(raffAppDidActivate:),
                Some(NSWorkspaceDidActivateApplicationNotification),
                None,
            );
        }
        // One observer for the process lifetime; it is never removed, and the
        // notification center would dangle if it were dropped here.
        std::mem::forget(observer);
    });
}

impl ActivationObserver {
    fn new() -> Retained<Self> {
        let this = Self::alloc().set_ivars(());
        unsafe { msg_send![super(this), init] }
    }
}

/// Ordinary (Dock-visible) running apps, for the exclusion-list picker.
pub fn running_apps() -> Vec<(String, String)> {
    use objc2_app_kit::NSApplicationActivationPolicy;
    let ws = NSWorkspace::sharedWorkspace();
    let mut apps: Vec<(String, String)> = ws
        .runningApplications()
        .iter()
        .filter(|a| a.activationPolicy() == NSApplicationActivationPolicy::Regular)
        .filter_map(|a| {
            let name = a.localizedName()?.to_string();
            let bundle = a.bundleIdentifier()?.to_string();
            Some((name, bundle))
        })
        .collect();
    apps.sort();
    apps.dedup_by(|a, b| a.1 == b.1);
    apps
}

pub fn activate_app(pid: i32) {
    if pid <= 0 {
        return;
    }
    if let Some(app) = NSRunningApplication::runningApplicationWithProcessIdentifier(pid) {
        app.activateWithOptions(NSApplicationActivationOptions::ActivateIgnoringOtherApps);
    }
}

/// Synthesizes ⌘V in the frontmost app. Requires the Accessibility permission;
/// without it the events are silently dropped by macOS.
pub fn send_cmd_v() -> bool {
    use core_graphics::event::{CGEvent, CGEventFlags, CGEventTapLocation};
    use core_graphics::event_source::{CGEventSource, CGEventSourceStateID};

    const KEY_V: u16 = 9; // kVK_ANSI_V
    let Ok(source) = CGEventSource::new(CGEventSourceStateID::HIDSystemState) else {
        return false;
    };
    let (Ok(down), Ok(up)) = (
        CGEvent::new_keyboard_event(source.clone(), KEY_V, true),
        CGEvent::new_keyboard_event(source, KEY_V, false),
    ) else {
        return false;
    };
    down.set_flags(CGEventFlags::CGEventFlagCommand);
    up.set_flags(CGEventFlags::CGEventFlagCommand);
    down.post(CGEventTapLocation::HID);
    std::thread::sleep(std::time::Duration::from_millis(25));
    up.post(CGEventTapLocation::HID);
    true
}

/// The .app bundle containing the running executable, if any
/// (…/Raff.app/Contents/MacOS/raff → …/Raff.app). `None` in dev mode.
pub fn app_bundle_path() -> Option<std::path::PathBuf> {
    let exe = std::env::current_exe().ok()?;
    let bundle = exe.parent()?.parent()?.parent()?;
    (bundle.extension()? == "app").then(|| bundle.to_path_buf())
}

/// Relaunches the packaged app exactly once, after this process has fully
/// exited: a detached `/bin/sh` polls the pid (10 Hz, ~20 s cap) and only then
/// hands the bundle to LaunchServices. The wait is what makes the relaunch
/// safe with the single-instance plugin — launching while the old process
/// still holds the instance socket would make the new one forward its argv
/// and exit (i.e. no relaunch at all). `open` without `-n` never creates a
/// second process: if the cap is ever hit with the old instance alive, it
/// merely activates it — no duplicate tray, no relaunch loop. `--settings`
/// is forwarded so the fresh instance reopens the settings surface.
pub fn spawn_relauncher(bundle: &std::path::Path, pid: u32) -> Result<(), String> {
    use std::process::{Command, Stdio};
    // The bundle path travels as "$0" (never interpolated into the script).
    let script = format!(
        "i=0; while kill -0 {pid} 2>/dev/null && [ $i -lt 200 ]; do sleep 0.1; i=$((i+1)); done; \
         exec /usr/bin/open \"$0\" --args --settings"
    );
    Command::new("/bin/sh")
        .arg("-c")
        .arg(script)
        .arg(bundle)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .map(|_| ())
        .map_err(|err| format!("تعذّر تشغيل Raff بعد التحديث: {err}"))
}

/// The official Raff repository. Hardcoded on purpose: the About window's link
/// must be able to open this URL and nothing else, so no URL ever crosses the
/// IPC boundary from the webview.
pub const REPOSITORY_URL: &str = "https://github.com/iSltanX/Raff";

pub fn open_repository() {
    let _ = std::process::Command::new("open")
        .arg(REPOSITORY_URL)
        .spawn();
}

pub fn open_accessibility_pane() {
    let _ = std::process::Command::new("open")
        .arg("x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility")
        .spawn();
}

// ─── Accessibility FFI (the only unsafe in the crate) ────────────────────────

#[link(name = "ApplicationServices", kind = "framework")]
extern "C" {
    fn AXIsProcessTrusted() -> bool;
    fn AXIsProcessTrustedWithOptions(options: core_foundation::dictionary::CFDictionaryRef)
        -> bool;
    static kAXTrustedCheckOptionPrompt: core_foundation::string::CFStringRef;
}

pub fn ax_trusted() -> bool {
    // SAFETY: zero-argument query into ApplicationServices; no memory crosses
    // the boundary.
    unsafe { AXIsProcessTrusted() }
}

/// Asks macOS to show the "allow Accessibility" prompt (also registers the app
/// in the System Settings list). Returns the current trust status.
pub fn ax_prompt() -> bool {
    use core_foundation::base::TCFType;
    use core_foundation::boolean::CFBoolean;
    use core_foundation::dictionary::CFDictionary;
    use core_foundation::string::CFString;

    // SAFETY: kAXTrustedCheckOptionPrompt is a constant CFString owned by the
    // system; wrap_under_get_rule retains it. The dictionary outlives the call,
    // which does not keep references past its return.
    unsafe {
        let key = CFString::wrap_under_get_rule(kAXTrustedCheckOptionPrompt);
        let options = CFDictionary::from_CFType_pairs(&[(
            key.as_CFType(),
            CFBoolean::true_value().as_CFType(),
        )]);
        AXIsProcessTrustedWithOptions(options.as_concrete_TypeRef())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn act(at: Instant, bundle: &str) -> Activation {
        Activation {
            at,
            app: FrontApp {
                pid: 0,
                name: bundle.into(),
                bundle_id: bundle.into(),
            },
        }
    }

    fn ago(now: Instant, ms: u64) -> Instant {
        now.checked_sub(Duration::from_millis(ms)).unwrap()
    }

    const WINDOW: Duration = Duration::from_millis(350);

    #[test]
    fn an_excluded_app_inside_the_window_is_caught_even_when_it_is_not_the_last_one() {
        let now = Instant::now();
        // Copied from the password manager, then ⌘-Tabbed away before the
        // poll noticed — the case that defeats asking who is frontmost now.
        let log = vec![
            act(ago(now, 4_000), "com.apple.Safari"),
            act(ago(now, 300), "com.agilebits.onepassword7"),
            act(ago(now, 40), "com.apple.Terminal"),
        ];
        let excluded = vec!["com.agilebits.onepassword7".to_string()];

        assert_ne!(log.last().unwrap().app.bundle_id, excluded[0]);
        assert!(window_has_excluded(&log, &excluded, now, WINDOW));
    }

    #[test]
    fn an_excluded_app_that_held_the_front_all_along_is_caught() {
        let now = Instant::now();
        let log = vec![act(ago(now, 9_000), "com.apple.Notes")];
        let excluded = vec!["com.apple.Notes".to_string()];

        assert!(window_has_excluded(&log, &excluded, now, WINDOW));
    }

    #[test]
    fn an_excluded_app_left_before_the_window_opened_is_not_caught() {
        let now = Instant::now();
        let log = vec![
            act(ago(now, 9_000), "com.apple.Notes"),
            act(ago(now, 2_000), "com.apple.Terminal"),
        ];
        let excluded = vec!["com.apple.Notes".to_string()];

        assert!(!window_has_excluded(&log, &excluded, now, WINDOW));
    }

    #[test]
    fn the_source_is_who_held_the_front_when_the_window_opened() {
        let now = Instant::now();
        let log = vec![
            act(ago(now, 4_000), "com.apple.Safari"),
            act(ago(now, 40), "com.apple.Terminal"),
        ];

        assert_eq!(
            front_at(&log, now, WINDOW).map(|a| a.bundle_id),
            Some("com.apple.Safari".to_string())
        );
    }

    #[test]
    fn an_empty_log_attributes_nothing() {
        assert!(front_at(&[], Instant::now(), WINDOW).is_none());
    }
}
