//! Thin macOS boundary: NSPasteboard, frontmost app, ⌘V synthesis, Accessibility.
//!
//! Everything here goes through the audited safe bindings of `objc2-app-kit` /
//! `core-graphics`. The only `unsafe` in the whole crate is the Accessibility
//! (AX) C FFI at the bottom of this file, each call documented with a SAFETY note.

use objc2_app_kit::{
    NSApplicationActivationOptions, NSPasteboard, NSRunningApplication, NSWorkspace,
};
use objc2_foundation::{NSData, NSString};

/// Pasteboard flags set by password managers and other sensitive sources.
/// Content carrying these must never be stored (see plan §5).
const CONCEALED_TYPES: [&str; 2] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
];

const TYPE_TEXT: &str = "public.utf8-plain-text";
const TYPE_HTML: &str = "public.html";
const TYPE_RTF: &str = "public.rtf";
const TYPE_PNG: &str = "public.png";
const TYPE_TIFF: &str = "public.tiff";

/// Rich representations larger than this are not stored (keeps the JSON store lean).
const MAX_RICH_BYTES: usize = 256 * 1024;

/// Raw pasteboard content, as captured. `rtf`/`html` are kept so a normal paste
/// can restore formatting while "paste as plain text" writes only `text`.
#[derive(Default)]
pub struct RawClip {
    pub text: Option<String>,
    pub html: Option<String>,
    pub rtf: Option<Vec<u8>>,
    pub png: Option<Vec<u8>>,
    pub tiff: Option<Vec<u8>>,
}

#[derive(Clone, Debug, Default)]
pub struct FrontApp {
    pub pid: i32,
    pub name: String,
    pub bundle_id: String,
}

pub fn change_count() -> isize {
    NSPasteboard::generalPasteboard().changeCount()
}

pub fn has_concealed_type() -> bool {
    let pb = NSPasteboard::generalPasteboard();
    let Some(types) = pb.types() else {
        return false;
    };
    types
        .iter()
        .any(|t| CONCEALED_TYPES.contains(&t.to_string().as_str()))
}

pub fn read_clip() -> RawClip {
    let pb = NSPasteboard::generalPasteboard();
    let string_for = |t: &str| {
        pb.stringForType(&NSString::from_str(t))
            .map(|s| s.to_string())
    };
    let data_for = |t: &str| {
        pb.dataForType(&NSString::from_str(t))
            .map(|d| d.to_vec())
            .filter(|d| !d.is_empty())
    };

    let text = string_for(TYPE_TEXT);
    let html = string_for(TYPE_HTML).filter(|h| h.len() <= MAX_RICH_BYTES);
    let rtf = data_for(TYPE_RTF).filter(|d| d.len() <= MAX_RICH_BYTES);
    // Only bother with image data when there is no text representation.
    let (png, tiff) = if text.as_deref().map(|t| !t.trim().is_empty()) == Some(true) {
        (None, None)
    } else {
        (data_for(TYPE_PNG), data_for(TYPE_TIFF))
    };

    RawClip {
        text,
        html,
        rtf,
        png,
        tiff,
    }
}

/// Writes the given representations to the general pasteboard and returns the
/// new change count (so the monitor can skip our own write).
pub fn write_clip(
    text: Option<&str>,
    html: Option<&str>,
    rtf: Option<&[u8]>,
    png: Option<&[u8]>,
) -> isize {
    let pb = NSPasteboard::generalPasteboard();
    pb.clearContents();
    if let Some(t) = text {
        pb.setString_forType(&NSString::from_str(t), &NSString::from_str(TYPE_TEXT));
    }
    if let Some(h) = html {
        pb.setString_forType(&NSString::from_str(h), &NSString::from_str(TYPE_HTML));
    }
    if let Some(r) = rtf {
        pb.setData_forType(Some(&NSData::with_bytes(r)), &NSString::from_str(TYPE_RTF));
    }
    if let Some(p) = png {
        pb.setData_forType(Some(&NSData::with_bytes(p)), &NSString::from_str(TYPE_PNG));
    }
    pb.changeCount()
}

pub fn frontmost_app() -> FrontApp {
    let ws = NSWorkspace::sharedWorkspace();
    match ws.frontmostApplication() {
        Some(app) => FrontApp {
            pid: app.processIdentifier(),
            name: app
                .localizedName()
                .map(|s| s.to_string())
                .unwrap_or_default(),
            bundle_id: app
                .bundleIdentifier()
                .map(|s| s.to_string())
                .unwrap_or_default(),
        },
        None => FrontApp::default(),
    }
}

/// Ordinary (Dock-visible) running apps, for the exclusion-list picker.
pub fn running_apps() -> Vec<(String, String)> {
    use objc2_app_kit::NSApplicationActivationPolicy;
    let ws = NSWorkspace::sharedWorkspace();
    let mut apps: Vec<(String, String)> = ws
        .runningApplications()
        .iter()
        .filter(|a| a.activationPolicy() == NSApplicationActivationPolicy::Regular)
        .filter_map(|a| {
            let name = a.localizedName()?.to_string();
            let bundle = a.bundleIdentifier()?.to_string();
            Some((name, bundle))
        })
        .collect();
    apps.sort();
    apps.dedup_by(|a, b| a.1 == b.1);
    apps
}

pub fn activate_app(pid: i32) {
    if pid <= 0 {
        return;
    }
    if let Some(app) = NSRunningApplication::runningApplicationWithProcessIdentifier(pid) {
        app.activateWithOptions(NSApplicationActivationOptions::ActivateIgnoringOtherApps);
    }
}

/// Synthesizes ⌘V in the frontmost app. Requires the Accessibility permission;
/// without it the events are silently dropped by macOS.
pub fn send_cmd_v() -> bool {
    use core_graphics::event::{CGEvent, CGEventFlags, CGEventTapLocation};
    use core_graphics::event_source::{CGEventSource, CGEventSourceStateID};

    const KEY_V: u16 = 9; // kVK_ANSI_V
    let Ok(source) = CGEventSource::new(CGEventSourceStateID::HIDSystemState) else {
        return false;
    };
    let (Ok(down), Ok(up)) = (
        CGEvent::new_keyboard_event(source.clone(), KEY_V, true),
        CGEvent::new_keyboard_event(source, KEY_V, false),
    ) else {
        return false;
    };
    down.set_flags(CGEventFlags::CGEventFlagCommand);
    up.set_flags(CGEventFlags::CGEventFlagCommand);
    down.post(CGEventTapLocation::HID);
    std::thread::sleep(std::time::Duration::from_millis(25));
    up.post(CGEventTapLocation::HID);
    true
}

/// Applies an .icns file as the app bundle's Finder icon via
/// `NSWorkspace.setIcon(_:forFile:options:)` — the official, documented
/// custom-icon mechanism (same as pasting an icon in Finder's Get Info).
/// Persistent, reversible, and does not touch LaunchServices or caches.
/// Returns false when not running from an .app bundle (dev mode) or on error.
pub fn set_bundle_icon(icns_path: &std::path::Path) -> bool {
    use objc2::AllocAnyThread;
    use objc2_app_kit::{NSImage, NSWorkspace, NSWorkspaceIconCreationOptions};

    let Some(bundle) = app_bundle_path() else {
        return false; // dev mode: bare binary, no bundle to decorate
    };
    let Some(icns) = icns_path.to_str() else {
        return false;
    };
    let Some(image) = NSImage::initWithContentsOfFile(NSImage::alloc(), &NSString::from_str(icns))
    else {
        eprintln!("raff: could not load icon image: {icns}");
        return false;
    };
    NSWorkspace::sharedWorkspace().setIcon_forFile_options(
        Some(&image),
        &NSString::from_str(&bundle.to_string_lossy()),
        NSWorkspaceIconCreationOptions(0),
    )
}

/// The .app bundle containing the running executable, if any
/// (…/Raff.app/Contents/MacOS/raff → …/Raff.app).
fn app_bundle_path() -> Option<std::path::PathBuf> {
    let exe = std::env::current_exe().ok()?;
    let bundle = exe.parent()?.parent()?.parent()?;
    (bundle.extension()? == "app").then(|| bundle.to_path_buf())
}

/// Whether the app's effective appearance is Dark, read from
/// `NSApp.effectiveAppearance` — the authoritative, in-process signal that is
/// already current by the time Tauri emits its `ThemeChanged` event (that event
/// is derived from this same appearance). Used to pick the Automatic app-icon
/// variant while following the system. Must be called on the main thread.
pub fn app_appearance_is_dark() -> bool {
    use objc2::MainThreadMarker;
    use objc2_app_kit::{NSAppearanceNameAqua, NSAppearanceNameDarkAqua, NSApplication};
    use objc2_foundation::NSArray;

    let Some(mtm) = MainThreadMarker::new() else {
        return false;
    };
    let appearance = NSApplication::sharedApplication(mtm).effectiveAppearance();
    // SAFETY: the two names are constant NSString globals owned by AppKit.
    let (aqua, dark) = unsafe { (NSAppearanceNameAqua, NSAppearanceNameDarkAqua) };
    let names = NSArray::from_slice(&[aqua, dark]);
    match appearance.bestMatchFromAppearancesWithNames(&names) {
        Some(best) => *best == *dark,
        None => false,
    }
}

pub fn open_accessibility_pane() {
    let _ = std::process::Command::new("open")
        .arg("x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility")
        .spawn();
}

// ─── Accessibility FFI (the only unsafe in the crate) ────────────────────────

#[link(name = "ApplicationServices", kind = "framework")]
extern "C" {
    fn AXIsProcessTrusted() -> bool;
    fn AXIsProcessTrustedWithOptions(
        options: core_foundation::dictionary::CFDictionaryRef,
    ) -> bool;
    static kAXTrustedCheckOptionPrompt: core_foundation::string::CFStringRef;
}

pub fn ax_trusted() -> bool {
    // SAFETY: zero-argument query into ApplicationServices; no memory crosses
    // the boundary.
    unsafe { AXIsProcessTrusted() }
}

/// Asks macOS to show the "allow Accessibility" prompt (also registers the app
/// in the System Settings list). Returns the current trust status.
pub fn ax_prompt() -> bool {
    use core_foundation::base::TCFType;
    use core_foundation::boolean::CFBoolean;
    use core_foundation::dictionary::CFDictionary;
    use core_foundation::string::CFString;

    // SAFETY: kAXTrustedCheckOptionPrompt is a constant CFString owned by the
    // system; wrap_under_get_rule retains it. The dictionary outlives the call,
    // which does not keep references past its return.
    unsafe {
        let key = CFString::wrap_under_get_rule(kAXTrustedCheckOptionPrompt);
        let options = CFDictionary::from_CFType_pairs(&[(
            key.as_CFType(),
            CFBoolean::true_value().as_CFType(),
        )]);
        AXIsProcessTrustedWithOptions(options.as_concrete_TypeRef())
    }
}
