//! Thin macOS boundary: NSPasteboard, frontmost app, ⌘V synthesis, Accessibility.
//!
//! Everything here goes through audited `objc2-app-kit` / `core-graphics`
//! bindings. The two unavoidable `unsafe` boundaries (an AppKit dictionary's
//! erased value type and the Accessibility C FFI) each carry a local SAFETY
//! argument.

use objc2::runtime::AnyObject;
use objc2_app_kit::{
    NSApplicationActivationOptions, NSBitmapImageFileType, NSBitmapImageRep,
    NSBitmapImageRepPropertyKey, NSPasteboard, NSRunningApplication, NSWorkspace,
};
use objc2_foundation::{MainThreadMarker, NSData, NSDictionary, NSString};

/// True when the caller is already on the AppKit main thread.
///
/// `MainThreadMarker::new()` is `Some` only on the main thread, which is
/// exactly the question, and it costs one `NSThread.isMainThread` check.
pub fn is_main_thread() -> bool {
    MainThreadMarker::new().is_some()
}

/// Queues `work` onto the main thread via libdispatch, without blocking.
///
/// This deliberately does NOT go through `AppHandle::run_on_main_thread`.
/// That posts to tao's event-loop proxy, and tao only drains that queue while
/// it is processing events — but Raff is an accessory (`LSUIElement`) app that
/// sits with no visible window most of the time, so its loop is parked and
/// nothing drains. Measured on a cold launch, a panel-show posted that way
/// took 2.5 SECONDS to run, and sometimes did not run at all until an
/// unrelated event happened along. Waking CFRunLoop first does not help: the
/// loop wakes, but tao still is not iterating, so its queue stays untouched.
///
/// libdispatch's main queue is drained by AppKit's own run-loop integration,
/// which is always installed, so work lands on the next turn regardless of
/// what tao is doing. `exec_async` (not `exec_sync`/`run_on_main`, which
/// block and could deadlock against a caller already holding a lock the main
/// thread wants) keeps the calling thread free.
pub fn dispatch_to_main<F: FnOnce() + Send + 'static>(work: F) {
    dispatch2::DispatchQueue::main().exec_async(work);
}

/// Pasteboard flags set by password managers and other sensitive sources.
/// Content carrying these must never be stored (see plan §5).
const CONCEALED_TYPES: [&str; 2] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
];

const TYPE_TEXT: &str = "public.utf8-plain-text";
const TYPE_HTML: &str = "public.html";
const TYPE_RTF: &str = "public.rtf";
const TYPE_PNG: &str = "public.png";
const TYPE_TIFF: &str = "public.tiff";

/// Rich representations larger than this are not stored (keeps the JSON store lean).
const MAX_RICH_BYTES: usize = 256 * 1024;

/// Raw pasteboard content, as captured. `rtf`/`html` are kept so a normal paste
/// can restore formatting while "paste as plain text" writes only `text`.
#[derive(Default)]
pub struct RawClip {
    pub text: Option<String>,
    pub html: Option<String>,
    pub rtf: Option<Vec<u8>>,
    pub png: Option<Vec<u8>>,
    pub tiff: Option<Vec<u8>>,
}

#[derive(Clone, Debug, Default)]
pub struct FrontApp {
    pub pid: i32,
    pub name: String,
    pub bundle_id: String,
}

pub fn change_count() -> isize {
    NSPasteboard::generalPasteboard().changeCount()
}

pub fn has_concealed_type() -> bool {
    let pb = NSPasteboard::generalPasteboard();
    let Some(types) = pb.types() else {
        return false;
    };
    types
        .iter()
        .any(|t| CONCEALED_TYPES.contains(&t.to_string().as_str()))
}

pub fn read_clip() -> RawClip {
    let pb = NSPasteboard::generalPasteboard();
    let string_for = |t: &str| {
        pb.stringForType(&NSString::from_str(t))
            .map(|s| s.to_string())
    };
    let data_for = |t: &str| {
        pb.dataForType(&NSString::from_str(t))
            .map(|d| d.to_vec())
            .filter(|d| !d.is_empty())
    };

    let text = string_for(TYPE_TEXT);
    let html = string_for(TYPE_HTML).filter(|h| h.len() <= MAX_RICH_BYTES);
    let rtf = data_for(TYPE_RTF).filter(|d| d.len() <= MAX_RICH_BYTES);
    // Only bother with image data when there is no text representation.
    let (png, tiff) = if text.as_deref().map(|t| !t.trim().is_empty()) == Some(true) {
        (None, None)
    } else {
        (data_for(TYPE_PNG), data_for(TYPE_TIFF))
    };

    RawClip {
        text,
        html,
        rtf,
        png,
        tiff,
    }
}

/// Writes the given representations to the general pasteboard and returns the
/// new change count only when at least one requested representation was
/// accepted (so callers never report copy/paste success for a rejected write).
pub fn write_clip(
    text: Option<&str>,
    html: Option<&str>,
    rtf: Option<&[u8]>,
    png: Option<&[u8]>,
) -> Option<isize> {
    let pb = NSPasteboard::generalPasteboard();
    pb.clearContents();
    let mut accepted = false;
    if let Some(t) = text {
        accepted |= pb.setString_forType(&NSString::from_str(t), &NSString::from_str(TYPE_TEXT));
    }
    if let Some(h) = html {
        accepted |= pb.setString_forType(&NSString::from_str(h), &NSString::from_str(TYPE_HTML));
    }
    if let Some(r) = rtf {
        accepted |= pb.setData_forType(Some(&NSData::with_bytes(r)), &NSString::from_str(TYPE_RTF));
    }
    if let Some(p) = png {
        accepted |= pb.setData_forType(Some(&NSData::with_bytes(p)), &NSString::from_str(TYPE_PNG));
    }
    accepted.then(|| pb.changeCount())
}

pub fn frontmost_app() -> FrontApp {
    let ws = NSWorkspace::sharedWorkspace();
    match ws.frontmostApplication() {
        Some(app) => FrontApp {
            pid: app.processIdentifier(),
            name: app
                .localizedName()
                .map(|s| s.to_string())
                .unwrap_or_default(),
            bundle_id: app
                .bundleIdentifier()
                .map(|s| s.to_string())
                .unwrap_or_default(),
        },
        None => FrontApp::default(),
    }
}

/// The Finder icon of an installed application, normalized to PNG bytes.
///
/// Raff renders the real source-app icon at 20pt inside a compact 30pt slot at
/// the end of every clipboard row. Resolved through the documented `NSWorkspace` pair
/// (`URLForApplicationWithBundleIdentifier` → `iconForFile`); returns `None`
/// when the bundle id is unknown or not installed. AppKit owns the TIFF → PNG
/// conversion because some modern app icons (including OpenAI's) use TIFF
/// representations the Rust `image` decoder cannot reliably read. AppKit —
/// main thread only.
pub fn app_icon_png(bundle_id: &str) -> Option<Vec<u8>> {
    if bundle_id.is_empty() {
        return None;
    }
    let ws = NSWorkspace::sharedWorkspace();
    let url = ws.URLForApplicationWithBundleIdentifier(&NSString::from_str(bundle_id))?;
    let path = url.path()?;
    let image = ws.iconForFile(&path);
    let tiff = image.TIFFRepresentation()?;
    let bitmap = NSBitmapImageRep::imageRepWithData(&tiff)?;
    let properties = NSDictionary::<NSBitmapImageRepPropertyKey, AnyObject>::dictionary();
    // SAFETY: AppKit requires an NSDictionary whose values match known image
    // property keys. The dictionary is empty, so it cannot contain a value of
    // the wrong type and merely requests the default PNG representation.
    let png = unsafe {
        bitmap.representationUsingType_properties(NSBitmapImageFileType::PNG, &properties)
    }?;
    Some(png.to_vec())
}

/// Ordinary (Dock-visible) running apps, for the exclusion-list picker.
pub fn running_apps() -> Vec<(String, String)> {
    use objc2_app_kit::NSApplicationActivationPolicy;
    let ws = NSWorkspace::sharedWorkspace();
    let mut apps: Vec<(String, String)> = ws
        .runningApplications()
        .iter()
        .filter(|a| a.activationPolicy() == NSApplicationActivationPolicy::Regular)
        .filter_map(|a| {
            let name = a.localizedName()?.to_string();
            let bundle = a.bundleIdentifier()?.to_string();
            Some((name, bundle))
        })
        .collect();
    apps.sort();
    apps.dedup_by(|a, b| a.1 == b.1);
    apps
}

pub fn activate_app(pid: i32) {
    if pid <= 0 {
        return;
    }
    if let Some(app) = NSRunningApplication::runningApplicationWithProcessIdentifier(pid) {
        app.activateWithOptions(NSApplicationActivationOptions::ActivateIgnoringOtherApps);
    }
}

/// Synthesizes ⌘V in the frontmost app. Requires the Accessibility permission;
/// without it the events are silently dropped by macOS.
pub fn send_cmd_v() -> bool {
    use core_graphics::event::{CGEvent, CGEventFlags, CGEventTapLocation};
    use core_graphics::event_source::{CGEventSource, CGEventSourceStateID};

    const KEY_V: u16 = 9; // kVK_ANSI_V
    let Ok(source) = CGEventSource::new(CGEventSourceStateID::HIDSystemState) else {
        return false;
    };
    let (Ok(down), Ok(up)) = (
        CGEvent::new_keyboard_event(source.clone(), KEY_V, true),
        CGEvent::new_keyboard_event(source, KEY_V, false),
    ) else {
        return false;
    };
    down.set_flags(CGEventFlags::CGEventFlagCommand);
    up.set_flags(CGEventFlags::CGEventFlagCommand);
    down.post(CGEventTapLocation::HID);
    std::thread::sleep(std::time::Duration::from_millis(25));
    up.post(CGEventTapLocation::HID);
    true
}

/// The .app bundle containing the running executable, if any
/// (…/Raff.app/Contents/MacOS/raff → …/Raff.app). `None` in dev mode.
pub fn app_bundle_path() -> Option<std::path::PathBuf> {
    let exe = std::env::current_exe().ok()?;
    let bundle = exe.parent()?.parent()?.parent()?;
    (bundle.extension()? == "app").then(|| bundle.to_path_buf())
}

/// Relaunches the packaged app exactly once, after this process has fully
/// exited: a detached `/bin/sh` polls the pid (10 Hz, ~20 s cap) and only then
/// hands the bundle to LaunchServices. The wait is what makes the relaunch
/// safe with the single-instance plugin — launching while the old process
/// still holds the instance socket would make the new one forward its argv
/// and exit (i.e. no relaunch at all). `open` without `-n` never creates a
/// second process: if the cap is ever hit with the old instance alive, it
/// merely activates it — no duplicate tray, no relaunch loop. `--settings`
/// is forwarded so the fresh instance reopens the settings surface.
pub fn spawn_relauncher(bundle: &std::path::Path, pid: u32) -> Result<(), String> {
    use std::process::{Command, Stdio};
    // The bundle path travels as "$0" (never interpolated into the script).
    let script = format!(
        "i=0; while kill -0 {pid} 2>/dev/null && [ $i -lt 200 ]; do sleep 0.1; i=$((i+1)); done; \
         exec /usr/bin/open \"$0\" --args --settings"
    );
    Command::new("/bin/sh")
        .arg("-c")
        .arg(script)
        .arg(bundle)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .map(|_| ())
        .map_err(|err| format!("تعذّر تشغيل Raff بعد التحديث: {err}"))
}

/// The official Raff repository. Hardcoded on purpose: the About window's link
/// must be able to open this URL and nothing else, so no URL ever crosses the
/// IPC boundary from the webview.
pub const REPOSITORY_URL: &str = "https://github.com/iSltanX/Raff";

pub fn open_repository() {
    let _ = std::process::Command::new("open")
        .arg(REPOSITORY_URL)
        .spawn();
}

pub fn open_accessibility_pane() {
    let _ = std::process::Command::new("open")
        .arg("x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility")
        .spawn();
}

// ─── Accessibility FFI (the only unsafe in the crate) ────────────────────────

#[link(name = "ApplicationServices", kind = "framework")]
extern "C" {
    fn AXIsProcessTrusted() -> bool;
    fn AXIsProcessTrustedWithOptions(options: core_foundation::dictionary::CFDictionaryRef)
        -> bool;
    static kAXTrustedCheckOptionPrompt: core_foundation::string::CFStringRef;
}

pub fn ax_trusted() -> bool {
    // SAFETY: zero-argument query into ApplicationServices; no memory crosses
    // the boundary.
    unsafe { AXIsProcessTrusted() }
}

/// Asks macOS to show the "allow Accessibility" prompt (also registers the app
/// in the System Settings list). Returns the current trust status.
pub fn ax_prompt() -> bool {
    use core_foundation::base::TCFType;
    use core_foundation::boolean::CFBoolean;
    use core_foundation::dictionary::CFDictionary;
    use core_foundation::string::CFString;

    // SAFETY: kAXTrustedCheckOptionPrompt is a constant CFString owned by the
    // system; wrap_under_get_rule retains it. The dictionary outlives the call,
    // which does not keep references past its return.
    unsafe {
        let key = CFString::wrap_under_get_rule(kAXTrustedCheckOptionPrompt);
        let options = CFDictionary::from_CFType_pairs(&[(
            key.as_CFType(),
            CFBoolean::true_value().as_CFType(),
        )]);
        AXIsProcessTrustedWithOptions(options.as_concrete_TypeRef())
    }
}
